// One image per article, shared by the index cards and the article's own lead figure so the two always match.
// The images are ink illustrations generated by `npm run article-images` from the subjects in content/article-images.json.

import manifest from '../../content/article-images.json';

export type ArticleKind = 'writing' | 'research';

const imagePath = (slug: string) => `/images/articles/${slug}.webp`;

// Articles without a dedicated image get a generic illustration chosen from the slug, so a piece keeps the same one
// wherever it appears and does not change when newer articles shift the list.
export const fallbackImages = Object.keys(manifest.fallback).map(imagePath);

export function articleImage(kind: ArticleKind, slug: string): string {
  if (Object.hasOwn(manifest[kind], slug)) return imagePath(slug);
  let hash = 0;
  for (const char of slug) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  return fallbackImages[hash % fallbackImages.length];
}
